# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7779eed0b27302d845b6de092f67008f03497e428002d82b64a1144781b5464616d021e6aa890f795cb731b1dce4c9896dae956da3fd04d2ad1bda27f117252

test:
  secret_key_base: 78e288e3383f668000d4c4bd3290f078d73602caaee82db374e7c5124e0bff3a3316a6462e839ae4eac9820bf005cd11f292a49271cc06420058072c85ddf6b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
